### ISSUE TITLE
What Solutions are dependencies?

### ISSUE THREAD

**Issue by dialedin2014** [microsoft/Industry-Accelerator-Nonprofit#18]
Is there a reference document showing the Solutions in Dynamics 365 for Sales upon which this Accelerator depends?

**Comment by maryambaig** [comment]
It's a solution in itself. You can download and add to your base D365 instance. That's all it really needs. Depending on how you want to extend it, you can add other solutions, and addons.  That is all optional and depends on what you're trying to achieve. 

Hope this helps!

**Comment by dialedin2014** [comment]
Thank you for your quick response.

This seems to detail it well: [https://docs.microsoft.com/en-us/common-data-model/nfp-accelerator](url)
