### ISSUE TITLE
Trouble importing NonprofitOperationsToolkitFlows 1.1.3.5

### ISSUE THREAD

**Issue by vernius28939** [microsoft/Industry-Accelerator-Nonprofit#31]
Hi.
I've been trying to import NonprofitOperationsTookitFlows 1.1.3.5 and get an error for a missing component - new_sharedcommondataserviceforapps_ea70f which is a Connection Reference required by Planning Period - calculate Weekdays.

Thanks.

Randy

**Comment by klbyrd** [comment]
Hi @vernius28939, can you please try to import in make.powerapps.com instead of the old classic interface? We believe that is what causes this error. Thank you!

**Comment by vernius28939** [comment]
Hi @klbyrd.
I tried importing using make.powerapps.com and still got an error.  

Thanks.

**Comment by klbyrd** [comment]
@vernius28939 we have updated the flow. That should resolve your issue. https://github.com/microsoft/Industry-Accelerator-Nonprofit/releases/download/v3.0.3.0/NonprofitOperationsToolkitFlows_1_1_3_6_managed.zip
